debian/rsyslog.conf /etc/
debian/tmp/usr/sbin/
debian/tmp/usr/share/man/
debian/tmp/usr/lib/rsyslog/imfile.so
debian/tmp/usr/lib/rsyslog/imklog.so
debian/tmp/usr/lib/rsyslog/immark.so
debian/tmp/usr/lib/rsyslog/imtcp.so
debian/tmp/usr/lib/rsyslog/imudp.so
debian/tmp/usr/lib/rsyslog/imuxsock.so
debian/tmp/usr/lib/rsyslog/lmnet.so
debian/tmp/usr/lib/rsyslog/lmnetstrms.so
debian/tmp/usr/lib/rsyslog/lmnsd_ptcp.so
debian/tmp/usr/lib/rsyslog/lmregexp.so
debian/tmp/usr/lib/rsyslog/lmstrmsrv.so
debian/tmp/usr/lib/rsyslog/lmtcpclt.so
debian/tmp/usr/lib/rsyslog/lmtcpsrv.so
debian/tmp/usr/lib/rsyslog/lmzlibw.so
debian/tmp/usr/lib/rsyslog/ommail.so
